copy %2objs14\AZRetail\FedSrv\AllSrv.exe %1 /Y
copy %2objs14\AZRetail\FedSrv\AllSrv.PDB %1 /Y
copy %2objs14\AZRetail\AllSrvUI\AllSrvUI.exe %1 /Y
copy %2objs14\AZRetail\AllSrvUI\AllSrvUI.PDB %1 /Y
copy %2objs14\AZRetail\Lobby\AllLobby.exe %1 /Y
copy %2objs14\AZRetail\Lobby\AllLobby.PDB %1 /Y
copy %2objs14\AZRetail\Club\AllClub.exe %1 /Y
copy %2objs14\AZRetail\Club\AllClub.PDB %1 /Y
copy %2objs14\AZRetail\WinTrek\Allegiance.exe %1 /Y
copy %2objs14\AZRetail\WinTrek\Allegiance.PDB %1 /Y
copy %2objs14\AZRetail\AGC\AGC.dll %1 /Y
copy %2objs14\AZRetail\AGC\AGC.PDB %1 /Y
copy %2objs14\AZRetail\Test\TCObj\TCObj.dll %1 /Y
copy %2objs14\AZRetail\Test\TCObj\TCObj.pdb %1 /Y
copy %2objs14\AZRetail\Pigs\PigsLib\PigsLib.dll %1 /Y
copy %2objs14\AZRetail\Pigs\PigsLib\PigsLib.pdb %1 /Y
copy %2objs14\AZRetail\Pigs\PigAccts\PigAccts.exe %1 /Y
copy %2objs14\AZRetail\Pigs\PigAccts\PigAccts.pdb %1 /Y
copy %2objs14\AZRetail\Pigs\PigSrv\PigSrv.exe %1 /Y
copy %2objs14\AZRetail\Pigs\PigSrv\PigSrv.pdb %1 /Y
copy %2objs14\AZRetail\Pigs\PigConfig\PigConfig.exe %1 /Y
copy %2objs14\AZRetail\Pigs\PigConfig\PigConfig.pdb %1 /Y
copy %2objs14\AZRetail\AutoUpdate\AutoUpdate.exe %1 /Y
copy %2objs14\AZRetail\AutoUpdate\AutoUpdate.pdb %1 /Y
copy %2objs14\AZRetail\Reloader\Reloader.exe %1 /Y
copy %2objs14\AZRetail\Reloader\Reloader.pdb %1 /Y
copy "%VS140COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC140.MFC\mfc140u.dll" %1 /Y
copy "%VS140COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC140.CRT\msvcp140.dll" %1 /Y
copy "%VS140COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC140.CRT\vcruntime140.dll" %1 /Y
copy "%VS140COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC140.CRT\appcrt140.dll" %1 /Y
copy "%VS140COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC140.CRT\desktopcrt140.dll" %1 /Y
copy %2src\license.txt %1 /Y