copy %2objs10\AZRetail\FedSrv\AllSrv.exe %1 /Y
copy %2objs10\AZRetail\FedSrv\AllSrv.PDB %1 /Y
copy %2objs10\AZRetail\AllSrvUI\AllSrvUI.exe %1 /Y
copy %2objs10\AZRetail\AllSrvUI\AllSrvUI.PDB %1 /Y
copy %2objs10\AZRetail\Lobby\AllLobby.exe %1 /Y
copy %2objs10\AZRetail\Lobby\AllLobby.PDB %1 /Y
copy %2objs10\AZRetail\Club\AllClub.exe %1 /Y
copy %2objs10\AZRetail\Club\AllClub.PDB %1 /Y
copy %2objs10\AZRetail\WinTrek\Allegiance.exe %1 /Y
copy %2objs10\AZRetail\WinTrek\Allegiance.PDB %1 /Y
copy %2objs10\AZRetail\AGC\AGC.dll %1 /Y
copy %2objs10\AZRetail\AGC\AGC.PDB %1 /Y
copy %2objs10\AZRetail\Test\TCObj\TCObj.dll %1 /Y
copy %2objs10\AZRetail\Test\TCObj\TCObj.pdb %1 /Y
copy %2objs10\AZRetail\Pigs\PigsLib\PigsLib.dll %1 /Y
copy %2objs10\AZRetail\Pigs\PigsLib\PigsLib.pdb %1 /Y
copy %2objs10\AZRetail\Pigs\PigAccts\PigAccts.exe %1 /Y
copy %2objs10\AZRetail\Pigs\PigAccts\PigAccts.pdb %1 /Y
copy %2objs10\AZRetail\Pigs\PigSrv\PigSrv.exe %1 /Y
copy %2objs10\AZRetail\Pigs\PigSrv\PigSrv.pdb %1 /Y
copy %2objs10\AZRetail\Pigs\PigConfig\PigConfig.exe %1 /Y
copy %2objs10\AZRetail\Pigs\PigConfig\PigConfig.pdb %1 /Y
copy %2objs10\AZRetail\AutoUpdate\AutoUpdate.exe %1 /Y
copy %2objs10\AZRetail\AutoUpdate\AutoUpdate.pdb %1 /Y
copy %2objs10\AZRetail\Reloader\Reloader.exe %1 /Y
copy %2objs10\AZRetail\Reloader\Reloader.pdb %1 /Y
copy "%VS100COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC100.ATL\atl100.dll" %1 /Y
copy "%VS100COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC100.MFC\mfc100.dll" %1 /Y
copy "%VS100COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC100.CRT\msvcp100.dll" %1 /Y
copy "%VS100COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC100.CRT\msvcr100.dll" %1 /Y
copy %2src\license.txt %1 /Y