copy %2objs10\FZDebug\FedSrv\AllSrv.exe %1 /Y
copy %2objs10\FZDebug\AllSrvUI\AllSrvUI.exe %1 /Y
copy %2objs10\FZDebug\Lobby\AllLobby.exe %1 /Y
copy %2objs10\FZDebug\Lobby\AllClub.exe %1 /Y
copy %2objs10\FZDebug\WinTrek\Allegiance.exe %1 /Y
copy %2objs10\FZDebug\AGC\AGC.dll %1 /Y
copy %2objs10\FZDebug\Pigs\PigsLib\PigsLib.dll %1 /Y
copy %2objs10\FZRetail\Test\TCObj\TCObj.dll %1 /Y
copy %2objs10\FZDebug\Pigs\PigAccts\PigAccts.exe %1 /Y
copy %2objs10\FZDebug\Pigs\PigSrv\PigSrv.exe %1 /Y
copy %2objs10\FZDebug\Pigs\PigConfig\PigConfig.exe %1 /Y
copy %2objs10\FZRetail\AutoUpdate\AutoUpdate.exe %1 /Y
copy %2objs10\FZRetail\Reloader\Reloader.exe %1 /Y