copy %2objs12\AZDebug\FedSrv\AllSrv.exe %1 /Y
copy %2objs12\AZDebug\AllSrvUI\AllSrvUI.exe %1 /Y
copy %2objs12\AZDebug\Lobby\AllLobby.exe %1 /Y
copy %2objs12\AZDebug\Club\AllClub.exe %1 /Y
copy %2objs12\AZDebug\WinTrek\Allegiance.exe %1 /Y
copy %2objs12\AZDebug\AGC\AGC.dll %1 /Y
copy %2objs12\AZDebug\Pigs\PigsLib\PigsLib.dll %1 /Y
copy %2objs12\AZDebug\Test\TCObj\TCObj.dll %1 /Y
copy %2objs12\AZDebug\Pigs\PigAccts\PigAccts.exe %1 /Y
copy %2src\Pigs\PigAccts\PigAccts.ini %1 /Y
copy %2objs12\AZDebug\Pigs\PigSrv\PigSrv.exe %1 /Y
copy %2objs12\AZDebug\Pigs\PigConfig\PigConfig.exe %1 /Y
copy %2objs12\AZDebug\AutoUpdate\AutoUpdate.exe %1 /Y
copy %2objs12\AZDebug\Reloader\Reloader.exe %1 /Y