copy %2objs12\AZRetail\FedSrv\AllSrv.exe %1 /Y
copy %2objs12\AZRetail\FedSrv\AllSrv.PDB %1 /Y
copy %2objs12\AZRetail\AllSrvUI\AllSrvUI.exe %1 /Y
copy %2objs12\AZRetail\AllSrvUI\AllSrvUI.PDB %1 /Y
copy %2objs12\AZRetail\Lobby\AllLobby.exe %1 /Y
copy %2objs12\AZRetail\Lobby\AllLobby.PDB %1 /Y
copy %2objs12\AZRetail\Club\AllClub.exe %1 /Y
copy %2objs12\AZRetail\Club\AllClub.PDB %1 /Y
copy %2objs12\AZRetail\WinTrek\Allegiance.exe %1 /Y
copy %2objs12\AZRetail\WinTrek\Allegiance.PDB %1 /Y
copy %2objs12\AZRetail\AGC\AGC.dll %1 /Y
copy %2objs12\AZRetail\AGC\AGC.PDB %1 /Y
copy %2objs12\AZRetail\Test\TCObj\TCObj.dll %1 /Y
copy %2objs12\AZRetail\Test\TCObj\TCObj.pdb %1 /Y
copy %2objs12\AZRetail\Pigs\PigsLib\PigsLib.dll %1 /Y
copy %2objs12\AZRetail\Pigs\PigsLib\PigsLib.pdb %1 /Y
copy %2objs12\AZRetail\Pigs\PigAccts\PigAccts.exe %1 /Y
copy %2objs12\AZRetail\Pigs\PigAccts\PigAccts.pdb %1 /Y
copy %2objs12\AZRetail\Pigs\PigSrv\PigSrv.exe %1 /Y
copy %2objs12\AZRetail\Pigs\PigSrv\PigSrv.pdb %1 /Y
copy %2objs12\AZRetail\Pigs\PigConfig\PigConfig.exe %1 /Y
copy %2objs12\AZRetail\Pigs\PigConfig\PigConfig.pdb %1 /Y
copy %2objs12\AZRetail\AutoUpdate\AutoUpdate.exe %1 /Y
copy %2objs12\AZRetail\AutoUpdate\AutoUpdate.pdb %1 /Y
copy %2objs12\AZRetail\Reloader\Reloader.exe %1 /Y
copy %2objs12\AZRetail\Reloader\Reloader.pdb %1 /Y
copy "%VS120COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC120.MFC\mfc120.dll" %1 /Y
copy "%VS120COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC120.MFC\mfcm120.dll" %1 /Y
copy "%VS120COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC120.MFC\mfc120u.dll" %1 /Y
copy "%VS120COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC120.MFC\mfcm120u.dll" %1 /Y
copy "%VS120COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC120.MFCLOC\mfc120enu.dll" %1 /Y
copy "%VS120COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC120.CRT\msvcp120.dll" %1 /Y
copy "%VS120COMNTOOLS%..\..\VC\redist\x86\Microsoft.VC120.CRT\msvcr120.dll" %1 /Y
copy %2src\license.txt %1 /Y