/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "lobbyService_constants.h"

namespace lobbyThriftService {

const lobbyServiceConstants g_lobbyService_constants;

lobbyServiceConstants::lobbyServiceConstants() {
}

} // namespace

