/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef lobbyService_CONSTANTS_H
#define lobbyService_CONSTANTS_H

#include "lobbyService_types.h"

namespace lobbyThriftService {

class lobbyServiceConstants {
 public:
  lobbyServiceConstants();

};

extern const lobbyServiceConstants g_lobbyService_constants;

} // namespace

#endif
