// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "LobbyService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::lobbyThriftService;

class LobbyServiceHandler : virtual public LobbyServiceIf {
 public:
  LobbyServiceHandler() {
    // Your initialization goes here
  }

  void Login(LoginResponse& _return, const LoginRequest& request) {
    // Your implementation goes here
    printf("Login\n");
  }

  void ListServers(ListServersResponse& _return) {
    // Your implementation goes here
    printf("ListServers\n");
  }

  void JoinMission(JoinMissionResponse& _return, const JoinMissionRequest& request) {
    // Your implementation goes here
    printf("JoinMission\n");
  }

  void FindPlayer(FindPlayerResponse& _return, const FindPlayerRequest& request) {
    // Your implementation goes here
    printf("FindPlayer\n");
  }

  void CreateMission(CreateMissionResponse& _return, const CreateMissionRequest& request) {
    // Your implementation goes here
    printf("CreateMission\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<LobbyServiceHandler> handler(new LobbyServiceHandler());
  shared_ptr<TProcessor> processor(new LobbyServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

